"""Create pessoa, participa, contrato, colaborador, idealizador,
   aliado e projeto

Revision ID: 0173dbbf2270
Revises: 91979b40eb38
Create Date: 2020-08-17 10:32:12.721314-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0173dbbf2270'
down_revision = '91979b40eb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('nome', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('telefone', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_index(op.f('ix_pessoa_email'), 'pessoa', ['email'], unique=True)
    op.create_index(op.f('ix_pessoa_id'), 'pessoa', ['id'], unique=True)
    op.create_table('projeto',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('titulo', sa.String(), nullable=False),
                    sa.Column('necessidades', sa.String(), nullable=False),
                    sa.Column('is_private', sa.Boolean(), nullable=False),
                    sa.Column('objetivo', sa.String(), nullable=True),
                    sa.Column('area', sa.String(), nullable=False),
                    sa.Column('descricao', sa.String(), nullable=True),
                    sa.Column('publico_alvo', sa.String(), nullable=True),
                    sa.Column('monetizacao', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_projeto_id'), 'projeto', ['id'], unique=False)
    op.create_table('aliado',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('caracteristicas', sa.String(), nullable=True),
                    sa.Column('experiencia', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['pessoa.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('colaborador',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('caracteristicas', sa.String(), nullable=True),
                    sa.Column('experiencia', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['id'], ['pessoa.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('contrato',
                    sa.Column('pessoa_id', sa.Integer(), nullable=False),
                    sa.Column('projeto_id', sa.Integer(), nullable=False),
                    sa.Column('tipo', sa.String(), nullable=True),
                    sa.Column('tempo', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoa.id'], ),
                    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
                    sa.PrimaryKeyConstraint('pessoa_id', 'projeto_id')
                    )
    op.create_table('idealizador',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['id'], ['pessoa.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('participa',
                    sa.Column('idealizador_id', sa.Integer(), nullable=False),
                    sa.Column('colaborador_id', sa.Integer(), nullable=False),
                    sa.Column('aliado_id', sa.Integer(), nullable=False),
                    sa.Column('projeto_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['aliado_id'], ['aliado.id'], ),
                    sa.ForeignKeyConstraint(['colaborador_id'], [
                                            'colaborador.id'], ),
                    sa.ForeignKeyConstraint(['idealizador_id'], [
                                            'idealizador.id'], ),
                    sa.ForeignKeyConstraint(['projeto_id'], ['projeto.id'], ),
                    sa.PrimaryKeyConstraint(
                        'idealizador_id', 'colaborador_id', 'aliado_id',
                        'projeto_id')
                    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user',
    #                 sa.Column('id', sa.INTEGER(),
    #                           autoincrement=True, nullable=False),
    #                 sa.Column('email', sa.VARCHAR(length=50),
    #                           autoincrement=False, nullable=False),
    #                 sa.Column('first_name', sa.VARCHAR(length=100),
    #                           autoincrement=False, nullable=True),
    #                 sa.Column('last_name', sa.VARCHAR(length=100),
    #                           autoincrement=False, nullable=True),
    #                 sa.Column('address', sa.VARCHAR(length=100),
    #                           autoincrement=False, nullable=True),
    #                 sa.Column('hashed_password', sa.VARCHAR(length=100),
    #                           autoincrement=False, nullable=False),
    #                 sa.Column('is_active', sa.BOOLEAN(),
    #                           autoincrement=False, nullable=False),
    #                 sa.Column('is_superuser', sa.BOOLEAN(),
    #                           autoincrement=False, nullable=False),
    #                 sa.PrimaryKeyConstraint('id', name='user_pkey')
    #                 )
    op.drop_table('participa')
    op.drop_table('idealizador')
    op.drop_table('contrato')
    op.drop_table('colaborador')
    op.drop_table('aliado')
    op.drop_index(op.f('ix_projeto_id'), table_name='projeto')
    op.drop_table('projeto')
    op.drop_index(op.f('ix_pessoa_id'), table_name='pessoa')
    op.drop_index(op.f('ix_pessoa_email'), table_name='pessoa')
    op.drop_table('pessoa')
    # ### end Alembic commands ###
