"""Add cargo, vinculo and situacao to Experiencias

Revision ID: 022009e46c92
Revises: 1574169338b0
Create Date: 2020-09-12 06:58:44.892186-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022009e46c92'
down_revision = '1574169338b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_experiencia_academica', sa.Column('curso', sa.String(), nullable=True))
    op.add_column('tb_experiencia_academica', sa.Column('situacao', sa.String(), nullable=True))
    op.add_column('tb_experiencia_profissional', sa.Column('vinculo', sa.String(), nullable=True))
    op.add_column('tb_experiencia_projetos', sa.Column('cargo', sa.String(), nullable=True))
    op.add_column('tb_experiencia_projetos', sa.Column('situacao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_experiencia_projetos', 'situacao')
    op.drop_column('tb_experiencia_projetos', 'cargo')
    op.drop_column('tb_experiencia_profissional', 'vinculo')
    op.drop_column('tb_experiencia_academica', 'situacao')
    op.drop_column('tb_experiencia_academica', 'curso')
    # ### end Alembic commands ###
