"""add objetivo

Revision ID: 5c268df716d8
Revises: 1574169338b0
Create Date: 2020-09-16 10:22:27.803285-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c268df716d8'
down_revision = '1574169338b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
