"""teste

Revision ID: 89828782e976
Revises: 95c5de4217fe
Create Date: 2020-10-06 11:46:01.342952-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89828782e976'
down_revision = '95c5de4217fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_habilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_tb_habilidades_id'), 'tb_habilidades', ['id'], unique=False)
    op.create_table('tb_habilidades_pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('habilidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habilidade_id'], ['tb_habilidades.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_habilidades_pessoa_id'), 'tb_habilidades_pessoa', ['id'], unique=False)
    op.create_table('tb_habilidades_projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('habilidade_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['habilidade_id'], ['tb_habilidades.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['tb_projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_habilidades_projeto_id'), 'tb_habilidades_projeto', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tb_habilidades_projeto_id'), table_name='tb_habilidades_projeto')
    op.drop_table('tb_habilidades_projeto')
    op.drop_index(op.f('ix_tb_habilidades_pessoa_id'), table_name='tb_habilidades_pessoa')
    op.drop_table('tb_habilidades_pessoa')
    op.drop_index(op.f('ix_tb_habilidades_id'), table_name='tb_habilidades')
    op.drop_table('tb_habilidades')
    # ### end Alembic commands ###
