"""Split experience between projects, professional and academic

Revision ID: 91e33590f130
Revises: 667b8cfa3dbf
Create Date: 2020-09-03 07:03:21.366755-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e33590f130'
down_revision = '667b8cfa3dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_experiencia_academica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('instituicao', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('escolaridade', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_experiencia_academica_id'), 'tb_experiencia_academica', ['id'], unique=False)
    op.create_table('tb_experiencia_profissional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('organizacao', sa.String(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_experiencia_profissional_id'), 'tb_experiencia_profissional', ['id'], unique=False)
    op.create_table('tb_experiencia_projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tb_experiencia_projetos_id'), 'tb_experiencia_projetos', ['id'], unique=False)
    op.create_table('tb_exp_academica_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('experiencia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['tb_area.id'], ),
    sa.ForeignKeyConstraint(['experiencia_id'], ['tb_experiencia_academica.id'], ),
    sa.PrimaryKeyConstraint('id', 'area_id', 'experiencia_id')
    )
    op.create_index(op.f('ix_tb_exp_academica_area_id'), 'tb_exp_academica_area', ['id'], unique=False)
    op.create_table('tb_exp_profissional_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('experiencia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['tb_area.id'], ),
    sa.ForeignKeyConstraint(['experiencia_id'], ['tb_experiencia_profissional.id'], ),
    sa.PrimaryKeyConstraint('id', 'area_id', 'experiencia_id')
    )
    op.create_index(op.f('ix_tb_exp_profissional_area_id'), 'tb_exp_profissional_area', ['id'], unique=False)
    op.create_table('tb_exp_projeto_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('experiencia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['tb_area.id'], ),
    sa.ForeignKeyConstraint(['experiencia_id'], ['tb_experiencia_projetos.id'], ),
    sa.PrimaryKeyConstraint('id', 'area_id', 'experiencia_id')
    )
    op.create_index(op.f('ix_tb_exp_projeto_area_id'), 'tb_exp_projeto_area', ['id'], unique=False)
    op.drop_index('ix_tb_experiencia_area_id', table_name='tb_experiencia_area')
    op.drop_table('tb_experiencia_area')
    op.drop_index('ix_tb_experiencia_id', table_name='tb_experiencia')
    op.drop_table('tb_experiencia')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_experiencia',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('tb_experiencia_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organizacao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pessoa_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['tb_pessoa.id'], name='tb_experiencia_pessoa_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tb_experiencia_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_tb_experiencia_id', 'tb_experiencia', ['id'], unique=False)
    op.create_table('tb_experiencia_area',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('experiencia_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['tb_area.id'], name='tb_experiencia_area_area_id_fkey'),
    sa.ForeignKeyConstraint(['experiencia_id'], ['tb_experiencia.id'], name='tb_experiencia_area_experiencia_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'area_id', 'experiencia_id', name='tb_experiencia_area_pkey')
    )
    op.create_index('ix_tb_experiencia_area_id', 'tb_experiencia_area', ['id'], unique=False)
    op.drop_index(op.f('ix_tb_exp_projeto_area_id'), table_name='tb_exp_projeto_area')
    op.drop_table('tb_exp_projeto_area')
    op.drop_index(op.f('ix_tb_exp_profissional_area_id'), table_name='tb_exp_profissional_area')
    op.drop_table('tb_exp_profissional_area')
    op.drop_index(op.f('ix_tb_exp_academica_area_id'), table_name='tb_exp_academica_area')
    op.drop_table('tb_exp_academica_area')
    op.drop_index(op.f('ix_tb_experiencia_projetos_id'), table_name='tb_experiencia_projetos')
    op.drop_table('tb_experiencia_projetos')
    op.drop_index(op.f('ix_tb_experiencia_profissional_id'), table_name='tb_experiencia_profissional')
    op.drop_table('tb_experiencia_profissional')
    op.drop_index(op.f('ix_tb_experiencia_academica_id'), table_name='tb_experiencia_academica')
    op.drop_table('tb_experiencia_academica')
    # ### end Alembic commands ###
