"""Add data_criacao and data_atualizacao in Pessoa and Projeto

Revision ID: 95c5de4217fe
Revises: 022009e46c92
Create Date: 2020-09-30 10:55:21.318770-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c5de4217fe'
down_revision = '022009e46c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_pessoa', sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True, onupdate=sa.text('now()')))
    op.add_column('tb_projeto', sa.Column('data_atualizacao', sa.DateTime(timezone=True), nullable=True, onupdate=sa.text('now()')))
    op.add_column('tb_projeto', sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_projeto', 'data_criacao')
    op.drop_column('tb_projeto', 'data_atualizacao')
    op.drop_column('tb_pessoa', 'data_atualizacao')
    # ### end Alembic commands ###
