"""add foto_perfil

Revision ID: b9cb70f6c8ac
Revises: ecfc0fcb6703
Create Date: 2020-10-07 15:47:15.678536-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cb70f6c8ac'
down_revision = 'ecfc0fcb6703'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_pessoa', sa.Column('foto_perfil', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_pessoa', 'foto_perfil')
    # ### end Alembic commands ###
