"""Telefone can be null

Revision ID: d61367592f44
Revises: 0173dbbf2270
Create Date: 2020-08-18 11:33:53.765563-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61367592f44'
down_revision = '0173dbbf2270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pessoa', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_pessoa_id', table_name='pessoa')
    op.create_index(op.f('ix_pessoa_id'), 'pessoa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pessoa_id'), table_name='pessoa')
    op.create_index('ix_pessoa_id', 'pessoa', ['id'], unique=True)
    op.alter_column('pessoa', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
